[pytest]
python_files = test_*.py testDataDriven.py
markers =
    smoke: Quick sanity tests
    regression: full tets suite
    critical: critical tests
    ai: AI powered test
testpaths = tests
addopts = --env=qa
#In tests
#@pytest.mark.smoke
#def test_create_booking():
#def test_get_booking(self, booking_api):
#    ...

#@pytest.mark.regression
#def test_create_booking(self, booking_api, data):
