name: API Tests

on:
  push:
    branches: [main] #Trigger workflow on push to main branch
  pull_request:
    branches: [main] #Trigger workflow on PR to main branch

permissions:
  contents: write #allow workflow to push to gh-pages branch for allure report deployment

jobs:
  test:
    runs-on: ubuntu-latest #uses latest ubuntu runner (VM)
    steps:
      - name: Checkout code #downloads the repository code to the runner (VM)
        uses: actions/checkout@v5 

      - name: Set up Python
        uses: actions/setup-python@v5 #installs python on the runner
        with:
          python-version: '3.11'

      - name: Install dependencies #installs dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh

      - name: Start Ollama and pull model
        run:   |
          ollama serve &
          sleep 5
          ollama pull llama3.2.1b

      - name: Run tests
        env: #sets environment variables for the test run, these are read in auth_api.py
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          AI_PROVIDER: ollama
          AI_MODEL: llama3.2.1b
        run: |
          pytest --env=qa --alluredir=reports/allure-results
      - name: Install Allure Commandline #Install allure on command
        run: |
          npm install -g allure-commandline 

      - name: Generate Allure Report #converts raw data to HTML Report
        if: always() #Runs even if tests fails
        run: |
          npx allure-commandline generate reports/allure-results -o reports/allure-report --clean

      - name: Deploy report to GitHub Pages #Deploys HTML to Github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure-report

      - name: Post Allure Report URL #Shows link in actions summary page
        if: always()
        run: |
          echo "## Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "[Open Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY
    